all:
#	javac -encoding utf-8 Hello.java -classpath "../.."
#	javac -encoding utf-8 Frequencer.java -classpath "../.."
	javac -encoding utf-8 InformationEstimator.java -classpath "../.."
#	javac -encoding utf-8 TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.B183338/Hello
#	java -classpath "../.." s4.B183338/Frequencer
	java -classpath "../.." s4.B183338/InformationEstimator
#	java -classpath "../.." s4.B183338/TestCase
